#!/bin/sh
# shellcheck source=/dev/null

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Run command only on the specified host
host_cmd () {
    if [ "$(hostname)" = "$1" ]; then
        sh -c "$2"
    fi
}


feh --bg-scale "$HOME/pics/wallpaper.png"
setxkbmap fr oss
setxkbmap -option 'caps:swapescape'
host_cmd 'aji' 'nm-applet' &
i3
